version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: danydodson/danydodson-dev:prod
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:80"