version: '3'
services:

  client:
    build:
      context: ./
      dockerfile: dockerfile
    image: danydodson/danydodson
    tty: true
    container_name: danydodson
    volumes:
      - ./:/usr/src/app
      - nm_vol:/usr/src/app/node_modules
    ports:
      - 8000:8000
    networks:
      - main

volumes:
  nm_vol:

networks:
  main:
