version: '3.7'

services:
  client:
    build: .
    image: danydodson/danydodson-dev:dev
    volumes:
      - .:/usr/src/app
      - cache:/usr/src/app/.cache
      - public:/usr/src/app/public
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8000:8000
    networks:
      - frontend

volumes:
  cache:
  public:
  node_modules:

networks:
  frontend:
