version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: danydodson/danydodson-dev:dev
    tty: true
    volumes:
      - ./:/usr/src/app
      - node_mods:/usr/src/app/node_modules
    ports:
      - 8000:8000

volumes:
  node_mods:

