version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: dockerfile.dev
      target: build
    image: danydodson/danydodson-dev:dev
    tty: true
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    volumes:
      - .:/home/node/app
      - cache:/home/node/app/.cache
      - public:/home/node/app/public
      - node_modules:/home/node/app/node_modules
    ports:
      - 0.0.0.0:8000:8000
      - 0.0.0.0:9929:9929
      - 0.0.0.0:9230:9230
    networks:
      - frontend

volumes:
  cache:
  public:
  node_modules:

networks:
  frontend:
