version: '3.7'
services:

  client:
    build: .
    image: danydodson/dd_dev
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    volumes:
      - .:/usr/src/app
      - cache:/usr/src/app/.cache
      - public:/usr/src/app/public
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8000:8000
    networks:
      - main_net

volumes:
  cache:
  public:
  node_modules:

networks:
  main_net:
