version: '3'
services:

  client:
    build: .
    image: danydodson/dd_dev
    tty: true
    restart: 'unless-stopped'
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8000:8000
    networks:
      - main_net

volumes:
  node_modules:

networks:
  main_net:
